DROP DATABASE IF EXISTS tecstore;
CREATE DATABASE tecstore;

DROP user IF EXISTS 'user'@'localhost';
CREATE USER 'user'@'localhost' IDENTIFIED BY 'adminadmin';
GRANT ALL ON tecstore.* TO 'user'@'localhost';

USE tecstore;

DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS MERCE;
DROP TABLE IF EXISTS ORDINE;
DROP TABLE IF EXISTS TICKET;

CREATE TABLE CLIENTE(
	CF_CLIENTE CHAR(16) PRIMARY KEY NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	COGNOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL UNIQUE KEY,
    PASS VARCHAR(20) NOT NULL,
    CITTA VARCHAR(20) NOT NULL,
    VIA VARCHAR(30) NOT NULL,
    N_CIVICO INT NOT NULL,
    CAP INT NOT NULL,
    TIPO VARCHAR(30) NOT NULL 
);

CREATE TABLE MERCE(
	CODICE_MERCE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITOLO VARCHAR(20) NOT NULL,
    CATEGORIA VARCHAR(20) NOT NULL,
    DESCRIZIONE VARCHAR(50) NOT NULL,
    COSTO DOUBLE NOT NULL,
    IMMAGINE MEDIUMBLOB 
);
ALTER TABLE MERCE AUTO_INCREMENT=1000000000;

CREATE TABLE ORDINE(   
	CODICE_ORDINE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DATAORDINE VARCHAR(30) NOT NULL,
    MEZZO VARCHAR(30) NOT NULL,
    N_MERCI INT NOT NULL,
    TOTALE INT NOT NULL,
    METODODIPAGAMENTO VARCHAR(30) NOT NULL,
    N_CARTA CHAR(16) NOT NULL,
    CF_CLIENTE CHAR(16) NOT NULL,
	CITTA VARCHAR(20) NOT NULL,
    VIA VARCHAR(30) NOT NULL,
    N_CIVICO INT NOT NULL,
    CAP INT NOT NULL,
    STATO VARCHAR(20) NOT NULL,
    FOREIGN KEY(CF_CLIENTE) REFERENCES CLIENTE(CF_CLIENTE) 
						 ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TICKET(
	CODICE_TICKET INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITOLO VARCHAR(25) NOT NULL,
    DESCRIZIONE VARCHAR(50) NOT NULL,
    STATO VARCHAR(30) NOT NULL,
	CF_CLIENTE CHAR(16) NOT NULL,
    CODICE_ORDINE INT NOT NULL,
	FOREIGN KEY(CF_CLIENTE) REFERENCES CLIENTE(CF_CLIENTE) 
						 ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(CODICE_ORDINE) REFERENCES ORDINE(CODICE_ORDINE) 
						 ON DELETE CASCADE ON UPDATE CASCADE
);


INSERT INTO CLIENTE(CF_CLIENTE, NOME, COGNOME, EMAIL, PASS, CITTA, VIA, N_CIVICO, CAP, TIPO)
	VALUES ('MRCVCN98R05D390T','Vincenzo','Marcantuono','vyncy98@gmail.com','marcantuono','Campagna','Starzulella',18,84022,'Amministratore');
    
INSERT INTO CLIENTE(CF_CLIENTE, NOME, COGNOME, EMAIL, PASS, CITTA, VIA, N_CIVICO, CAP, TIPO)
	VALUES ('FRNFST00D12F236P','Francesco','Festa','fra@gmail.com','marcantuono','Avellino','Roma',1,80000,'Operatore');

INSERT INTO CLIENTE(CF_CLIENTE, NOME, COGNOME, EMAIL, PASS, CITTA, VIA, N_CIVICO, CAP, TIPO)
	VALUES ('PLOPTR97M17G487O','Paolo','Patrone','paolo@gmail.com','marcantuono','Salerno','Cappello',10,80000,'Cliente');
    
INSERT INTO MERCE(TITOLO, CATEGORIA, DESCRIZIONE, COSTO)
	VALUES ('HP ELITEBOOK 745 G2','PC','PC 8GB RAM',499);
 
INSERT INTO MERCE(TITOLO, CATEGORIA, DESCRIZIONE, COSTO)
	VALUES ('IPhone 12 ','Cellulare','IPhone 12 Pro Max 256gb',999);
    
INSERT INTO MERCE(TITOLO, CATEGORIA, DESCRIZIONE, COSTO)
	VALUES ('Asus VivoBook','PC','PC 8GB RAM 1 TB SSD',449);

INSERT INTO MERCE(TITOLO, CATEGORIA, DESCRIZIONE, COSTO)
	VALUES ('Canon EOS 1000D','Fotocamera','Fotocamera Canon',769);
    